# ワークフローの名前、Actions上に表示される
name: Hello, World!
# 何をアクションとするか
# この場合該当リポジトリにどのブランチでpushしても以下のjobが必ず実行される
on: push
 
jobs:
  # jobのkey名
  # 複数のjobを作成し他のjobから使用する際にはこのkey名を使用する
  # もしこのjobのnameを指定しなかった場合は、このkey名がnameとして使われる
  build:
    # jobの名前
    name: Greeting
    # 使用するOperating System
    runs-on: ubuntu-latest
    container: node:14.16
    # 実行する内容
    steps:
      - run: echo "Hello, World!"
